import forms from '@tailwindcss/forms'
import containerQueries from '@tailwindcss/container-queries'
import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#10131a',
        surface: '#10131a',
        'surface-dim': '#10131a',
        'surface-container-lowest': '#0b0e15',
        'surface-container-low': '#191b23',
        'surface-container': '#1d2027',
        'surface-container-high': '#272a31',
        'surface-container-highest': '#32353c',
        'surface-bright': '#363941',
        'surface-variant': '#32353c',
        'on-surface': '#e1e2ec',
        'on-surface-variant': '#c2c6d6',
        'on-background': '#e1e2ec',
        outline: '#8c909f',
        'outline-variant': '#424754',
        primary: '#adc6ff',
        'on-primary': '#002e6a',
        'primary-container': '#4d8eff',
        'on-primary-container': '#00285d',
        'primary-fixed': '#d8e2ff',
        'primary-fixed-dim': '#adc6ff',
        'on-primary-fixed': '#001a42',
        'on-primary-fixed-variant': '#004395',
        'inverse-primary': '#005ac2',
        'surface-tint': '#adc6ff',
        secondary: '#4edea3',
        'on-secondary': '#003824',
        'secondary-container': '#00a572',
        'on-secondary-container': '#00311f',
        'secondary-fixed': '#6ffbbe',
        'secondary-fixed-dim': '#4edea3',
        'on-secondary-fixed': '#002113',
        'on-secondary-fixed-variant': '#005236',
        tertiary: '#ffb95f',
        'on-tertiary': '#472a00',
        'tertiary-container': '#ca8100',
        'on-tertiary-container': '#3e2400',
        'tertiary-fixed': '#ffddb8',
        'tertiary-fixed-dim': '#ffb95f',
        'on-tertiary-fixed': '#2a1700',
        'on-tertiary-fixed-variant': '#653e00',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'inverse-surface': '#e1e2ec',
        'inverse-on-surface': '#2e3038',
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        base: '4px',
        'unit-1': '0.25rem',
        'unit-2': '0.5rem',
        'unit-4': '1rem',
        'unit-6': '1.5rem',
        'unit-8': '2rem',
        'container-max': '1440px',
        gutter: '1rem',
        'sidebar-width': '240px',
      },
      fontFamily: {
        display: ['Geist', 'sans-serif'],
        'headline-md': ['Geist', 'sans-serif'],
        'headline-sm': ['Geist', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'code-md': ['JetBrains Mono', 'monospace'],
        'code-sm': ['JetBrains Mono', 'monospace'],
        'label-caps': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        display: ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '1.4', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'code-md': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'code-sm': ['12px', { lineHeight: '1.4', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [forms, containerQueries],
} satisfies Config
